#!/bin/bash

# usage
cmdname=${0##*/}
function usage()
{
    echo "usage: ${cmdname} [-v VERSION] dir" 1>&2
    exit 1
}

version=3.5.3
# check options
while getopts v: option
do
    case ${option} in
	v)
	    version=${OPTARG}
	    ;;
	*)
	    usage
	    ;;
    esac
done
shift $((OPTIND - 1))

# check arguments
if [ $# -ne 1 ]; then
    usage
    exit 1
fi
dir="$1"

# main
if [ -e $dir ]; then
    echo "$dir already exists"
    exit 1
else
    mkdir $dir
fi
echo "layout python $(pythonz locate ${version})" > ${dir}/.envrc
direnv allow ${dir}
exit 0
